services:
  - type: web
    name: La-Ultima-Botella
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_NAME
        value: "La Ultima Botella"
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://la-ultima-botella.onrender.com
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /var/data/database.sqlite
      - key: CACHE_DRIVER
        value: file
      - key: SESSION_DRIVER
        value: file
      - key: QUEUE_CONNECTION
        value: sync
    disk:
      name: sqlite-data
      mountPath: /var/data
      sizeGB: 1
